name: focus-desk-suite # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
title: Focus Desk Planner
summary: Organize tasks and boost daily productivity.
description: A minimal yet powerful task manager designed to help you track goals, schedule activities, and maintain focus throughout your workday.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  focus-desk-suite:
    command: bin/focus-desk-suite-bin
    extensions: [gnome]
    plugs:
      - network
      - unity7
      - network-status

layout:
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0

parts:
  focus-desk-suite:
    plugin: dump
    source: .
    organize:
      focus-desk-suite-bin: bin/
